sonar.java.binaries property required
For latest Sonarcube cli builds - we need to specify binary

ReadMore at : https://stackoverflow.com/q/55939429/1525324

JenkinsError : ERROR: Error during SonarQube Scanner execution
org.sonar.java.AnalysisException: Please provide compiled classes of your project with sonar.java.binaries property